/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as GymRouteImport } from './routes/gym'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HabitsIndexRouteImport } from './routes/habits.index'
import { Route as HabitsHabitIdRouteImport } from './routes/habits.$habitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const GymRoute = GymRouteImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsHabitIdRoute = HabitsHabitIdRouteImport.update({
  id: '/habits/$habitId',
  path: '/habits/$habitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/gym': typeof GymRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/': typeof HabitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/gym': typeof GymRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits': typeof HabitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof CalendarRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/gym': typeof GymRoute
  '/review': typeof ReviewRoute
  '/settings': typeof SettingsRoute
  '/habits/$habitId': typeof HabitsHabitIdRoute
  '/habits/': typeof HabitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/gym'
    | '/review'
    | '/settings'
    | '/habits/$habitId'
    | '/habits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/gym'
    | '/review'
    | '/settings'
    | '/habits/$habitId'
    | '/habits'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calendar'
    | '/dashboard'
    | '/goals'
    | '/gym'
    | '/review'
    | '/settings'
    | '/habits/$habitId'
    | '/habits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalendarRoute: typeof CalendarRoute
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRoute
  GymRoute: typeof GymRoute
  ReviewRoute: typeof ReviewRoute
  SettingsRoute: typeof SettingsRoute
  HabitsHabitIdRoute: typeof HabitsHabitIdRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym': {
      id: '/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof GymRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/$habitId': {
      id: '/habits/$habitId'
      path: '/habits/$habitId'
      fullPath: '/habits/$habitId'
      preLoaderRoute: typeof HabitsHabitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalendarRoute: CalendarRoute,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRoute,
  GymRoute: GymRoute,
  ReviewRoute: ReviewRoute,
  SettingsRoute: SettingsRoute,
  HabitsHabitIdRoute: HabitsHabitIdRoute,
  HabitsIndexRoute: HabitsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
